### ISSUE TITLE
"Cheatsheet" cut off in dark mode 

### ISSUE THREAD

**Issue by michellew7** [neevaco/neeva-ios#2837]
![IMG_236170F6D685-1](https://user-images.githubusercontent.com/62567819/153282142-cd17f949-30ba-4647-bee8-08cd1b06971c.jpeg)

**Comment by EdwardJTL** [comment]
do we know what device this is running on? (OS and model) and which branch/commit this build was built from?
i don't know if darkmode is causing the issue. Dark mode should only change the colours, and the image asset is the same size...

**Comment by michellew7** [comment]
yep! iphone 11 pro, 1.26.8, iOs 15.2.1 @EdwardJTL

**Comment by EdwardJTL** [comment]
This issue was caused by the child view being too tall with the description text. the overlaysheet anchors the view on the bottom edge, and lays out the view upwards.
in the new intro screen, the text is only two lines. I verified that the issue is no longer there on iPhone 11 Pro. we can leave it for now.
