### ISSUE TITLE
Can end up with no toolbars

### ISSUE THREAD

**Issue by darinwf** [neevaco/neeva-ios#2869]
See video for repro steps:
https://user-images.githubusercontent.com/79867437/153902701-ccf28842-b0c1-44ad-998e-f9c95753f241.MP4

Not sure if this is the most reduced repro, but can repro by creating a new empty space and then tapping on the "Start searching" button, performing a search and then tapping on the "add to spaces" button.

**Comment by darinwf** [comment]
FYI @yozuysal

**Comment by yozuysal** [comment]
I feel like we might need to fine tune how showing toolbars and grid works right now. I also noticed animation weirdness with grid picker mostly due to the fact that now it is detached from the grid itself and its state is owned by toptoolbar. (which is seen as them animating independent of each other)

I feel like going to a switch model similar to TabContentHost might be a more reliable solution. (Will also help with extending to situations where we have other fullscreen UIs than browserview and cardgrid)
