### ISSUE TITLE
Binary failed to upload to TestFlight with XCFramework related changes

### ISSUE THREAD

**Issue by chassu** [neevaco/neeva-ios#2952]
Getting this error when I try to upload a build to TestFlight:

ITMS-90853: Invalid font - There was an error validating the font at 'Client.app/Frameworks/GCDWebServers.framework/GCDWebUploader.bundle/Contents/Resources/fonts/glyphicons-halflings-regular.woff'. Font not supported by platform.

For now, I have to revert #2923 and #2935 to upload a build successfully.

**Comment by darinwf** [comment]
@jed-fox-neeva @evancrow FYI

**Comment by evancrow** [comment]
Jed's been contributing under @j-f1  account recently @darinwf (fyi)

**Comment by j-f1** [comment]
Ah, I wonder if this script did something important. I removed it because the folder no longer existed, but it probably did end up somewhere inside of the `xcframework`.

https://github.com/neevaco/neeva-ios/pull/2923/files#diff-053ad7baef0cd20365abec6f2d6133fa7eed9440d908c9f92e1319c8d610d17fL5144-L5160

**Comment by darinwf** [comment]
> Ah, I wonder if this script did something important. I removed it because the folder no longer existed, but it probably did end up somewhere inside of the `xcframework`.
> 
> https://github.com/neevaco/neeva-ios/pull/2923/files#diff-053ad7baef0cd20365abec6f2d6133fa7eed9440d908c9f92e1319c8d610d17fL5144-L5160

Thanks for the tip @j-f1 !
