### ISSUE TITLE
After tapping yes on ShareSpaceIntroScreen Space isn't public

### ISSUE THREAD

**Issue by evancrow** [neevaco/neeva-ios#3466]
Steps to repro:

- Delete and reinstall the app
- Create space
- Share space via more button
- Tap `Yes! Share my space publicly`
- Would expect the Space to be public but it's still private

FYI @yozuysal @buracules

**Comment by buracules** [comment]
I can't reproduce this. Which version are you using? There was a problem with updating spaces i fixed that in here. https://github.com/neevaco/neeva-ios/pull/3443

**Comment by evancrow** [comment]
I saw this when I tapped `More` in the share menu when the Space wasn't shared yet (after reinstalling the app)

**Comment by buracules** [comment]
Oh now I get it. It is weird though same logic works when seenSpacesShareIntro is true.

**Comment by buracules** [comment]
Actually this isn't new we see this now because there is another bug. We can't see EmptySpaceView for empty spaces. 

As you can see the toggle is still of after i tapping yes.
https://user-images.githubusercontent.com/15333612/165799656-41bed7b6-d489-4b55-a6e9-17c87deee934.mp4

I am gonna fix the other issue first. Do you have any ideas what can cause this? 
I mean it looks OK to me actually.

**Comment by buracules** [comment]
Yes setting `isPublic = true` is not working for this but `spaceModel.changePublicACL(space: space, add: true)` is working.

**Comment by darinwf** [comment]
Removing label:release_blocker per chat w/ @yozuysal
