### ISSUE TITLE
Tab objects never deallocated

### ISSUE THREAD

**Issue by EdwardJTL** [neevaco/neeva-ios#3820]
## Expected behavior
Tab objects should be deallocated at some point.

## Actual behavior

Tab objects are persistent even after going into background. It appears that TabCardDetails is holding a strong reference to all the tab objects.

## Steps to reproduce the problem

1. Start with no tabs
2. Add a tab (not just a lazy one)
3. Close that tab
4. Repeat 2-4 as many times are you want
5. go into background and come back
6. observe number of persistent tabs (either via profiler or via xcode memory graph)

## Screenshots or recordings

<img width="2518" alt="Screen Shot 2022-06-09 at 3 25 12 PM" src="https://user-images.githubusercontent.com/44557675/172955318-d31153a2-5eb7-4d4b-b0e2-259459221019.png">

## Hardware and software

- Your device: 
- OS version: 
- App version: main @ 2dd9ab7c3b466efd40b61e334abe417ebcb9d825

**Comment by darinwf** [comment]
I think this is working as intended unless the `Tab` instances are no longer owned by the `TabManager`. Do we see any for which that is the case? We could probably switch to making `TabCardDetails` hold a weak reference to `Tab` objects.

**Comment by darinwf** [comment]
Alternatively, and maybe better, we should just make sure that `Tab.close()` is called whenever the `TabManager` drops its reference to a `Tab`.

**Comment by EdwardJTL** [comment]
The `Tab` instances here do not appear to be owned by the `TabManager` anymore. I agree that maybe `TabCardDetails` only needs a weak reference.
my issue with `Tab.close()` approach is that we will need manual effort to make sure that `Tab.close()` releases all the data that is no longed needed. For example, the fetched cheatsheet data remains in memory; we can find a way to release this data, but when we add some other stored properties in the future we have to remember to do that again.

**Comment by darinwf** [comment]
The downside to the weak reference however is that it means we complicate the code that uses `TabCardDetails`. It used to deal with `Tab` being optional (it did a lookup of `Tab` by ID), and there were a lot of problems with that. I worry using weak reference might bring some of those issues back.

Also, object release timing is not super deterministic in Swift. What happens if something else takes a reference to the `Tab`? We might find ourselves fighting these bugs continuously. In contrast, `Tab.close()` is a very deterministic point, and once we think to add something there, we can know that it will be forever taken care of.

I would start by going for that more deterministic approach :)

**Comment by EdwardJTL** [comment]
hmm maybe we should have a distinct between data that needs to be alive when webview is alive, and which ones need to always be alive even after the tab is closed.

**Comment by darinwf** [comment]
> hmm maybe we should have a distinct between data that needs to be alive when webview is alive, and which ones need to always be alive even after the tab is closed.

That's a good idea! Then `Tab.close()` would just be about nuking the corresponding object.

**Comment by jedireza** [comment]
Moved to ClickUp 🔒 https://app.clickup.com/t/3w3axa5
