### ISSUE TITLE
Spaces Very Flakey Overall

### ISSUE THREAD

**Issue by evancrow** [neevaco/neeva-ios#4121]
My general usage of spaces on mobile has not been great recently. 

Few issues I've found:
- [x] Re-ordering items doesn't save the first time, takes multiple tries to get it to save
- [x] Deleting an item from Space doesn't always work. Or it does, but it doesn't reflect that in the app (the item is still visible).
- [ ] Comments experience is poor #3942 
- [ ] Adding or changing an item doesn't save (if you close the space and re-open it still shows the original item)

Many of these issues have a common problem: the local version isn't working nicely with the GraphQL updates. Don't think this is a release blocker but should be fixed sometime soon.

cc @yozuysal @buracules @jonathangarelick @darinwf

**Comment by yozuysal** [comment]
Hi @evancrow , thanks for reporting this. I actually got a similar report over the weekend from a user. By flaky, do you mean these problems come or go independent of use case or do they only happen when you perform the actions in a certain order?

In order of importance, we should expect
- Add, delete any url to a space to work without any issues.
- Reordering to not revert back to original
- Deleting to be consistent across local and server side copy

I wouldn't prioritize comments highly wrt to the above. But all other three are pretty fundamental, so we should make sure they are working at all times. 

I can perform all three actions from my phone with 1.51.1. Anything you can share around version or device to better nail down the flakiness would be appreciated.

**Comment by evancrow** [comment]
> By flaky, do you mean these problems come or go independent of use case or do they only happen when you perform the actions in a certain order?

Independent of each other. I can recreate all of these on the latest TestFlight, on multiple devices (iPhone/iPad), and on different OS (15-16)

Repro for adding/deleting issues:
- Add/Delete an item
- Close SpaceDetailView
- Re-open, and changes are gone (reload the app, and they appear)

Repro for re-ordering flakiness:
- Same as above
- Also occurs after adding or deleting an item

**Comment by yozuysal** [comment]
hmm, ok. From what you describe, I think this might have to with the local updates we make right after edits and before any refreshes.

@buracules can you take a look? Let us know if you are having trouble with repro. (1.51.1 should contain all changes, I still can't repro) Let's try to get to the bottom of this today so that we can fix these for the next update.

**Comment by buracules** [comment]
I tried these steps with simulator(main) and testlight several times and still I couldn't reproduce this. Also i debug the code its still works the same when there is a local mutation it sets `spaceNeedsRefresh` and when `detailedSpace` is set refreshes that space.

Maybe we are getting an error from `getSpacesData`?

Also we can take same approach here since we know what the mutations are. We can change them locally without refresh.

**Comment by buracules** [comment]
When we create a space item we are assigning random id right now and thats cause the following problem.

If we delete this item before we refresh the space it will try to delete that item but it will not delete because we passed dummy id when we click undo it will create a copy of that item.

I think flakiness starts when we create an item.

I will try to update the space when we create an item.

**Comment by buracules** [comment]
I fixed the duplication issue also kinda fix the whole thing

https://user-images.githubusercontent.com/15333612/182487802-f0698c74-d297-484e-aef0-6010233260f4.mp4

Right now it shows the old items and updates the list. For this not to happen i have to remove items from spacestore as well but when i do that `undo` button doesnt work.

**Comment by darinwf** [comment]
I discussed w/ @jonathangarelick over Slack, and we agreed it makes sense to not block this week's release for this bug. Removing the release blocker label. Let's give ourselves a bit more time to do it right on `main` and not try to rush a fix. Thanks!
